### ISSUE TITLE
Form builder - toast/alert/flash messages

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#101]
Consistent with #79, implement pop-up informational messages.

Acceptance criteria:

- [x] Show messages on add pattern, delete pattern
- [x] Style with [USWDS Alert component](https://designsystem.digital.gov/components/alert/)
- [x] Implement best-practice timeout, and document on this ticket (5 seconds + 1 second for each additional 120 words)
- [x] Implement WCAG guidance for notifications

**Comment by espythomson** [comment]
@natashapl @danielnaab here is the Figma Toasts section, drawn from USWDS https://www.figma.com/file/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?type=design&node-id=115%3A34146&mode=design&t=bsYsQN3ez7DNifIl-1
