### ISSUE TITLE
Design files mgmt and documentation

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#198]
Provide recommendations for how to manage and organize Figma files going into phase 4.
```[tasklist]
### Tasks
- [x] Document is created and shared with team.
- [x] Pass at organizing Figma is complete to aid in onboarding new designer.
```

**Comment by emilylordahl** [comment]
Here is the job description for [open lead design role](https://docs.google.com/document/d/1nW2VmVuNm6qsHVA1dPjjLXZZKAPCcrgB_hn3QAkX6WE/edit?usp=sharing).

**Comment by emilylordahl** [comment]
Here are a few updates and resources for this ticket @jimmoffet:

- [Recommendations for Organizing Designs and Artifacts in Figma](https://docs.google.com/document/d/1zHu2ue-kFZuM3tht5tHnHz2dzt6f0S32_O05HhBumoY/edit) The full team (@natashapl, @danielnaab, @ethangardner, @espythomson) can also feel free to review and add comments.
- Broader [learnings and recommendations fr phase 4](https://docs.google.com/document/d/18bfAQUMvf8L1cNuqp52JbQzG1x5RZ_R0xI_tzv3fCAc/edit#heading=h.uk7s728jvvrv) based on my observations in phase 3. I've shared this doc with @danielnaab and Dan R. for visibility. 
- "Job Description" for the [open design lead role](https://docs.google.com/document/d/1nW2VmVuNm6qsHVA1dPjjLXZZKAPCcrgB_hn3QAkX6WE/edit?usp=sharing) on the team.

My goal with these resources and recommendations is to provide feedback for where I believe there is opportunity to improve the process, role descriptions and product going further into phase 4 as I off-board. Please reach out with any clarifications or questions. Thanks! I will move to In Review.
