### ISSUE TITLE
[Design] Mock-ups for instruction/overview page

### ISSUE THREAD

**Issue by emilylordahl** [GSA-TTS/atj-platform#256]
Reference #270 

There is a need to create introductory, official information that is not actionable (does not contain applicant questions). This can be done through a introductory page tape that does not require action from the applicant and will always come first in the list of pages in the application form. 

Design a page type (or other solution) for instructions or similar that enables form authors to add text content and/or the PDf ingestion mechanism can automatically create a instructional page-type from. The page's only action is for applicants to proceed to the next page. No applicant input is required.

@jimmoffet This issue was added as a result of the UX Concept testing in https://github.com/GSA-TTS/atj-platform/issues/116 . It needs further refinement and prioritization.

UX considers this a major feature/issue due to it coming up with some participants. Review details from the research in the [research report](https://docs.google.com/presentation/d/1qmmtHEboGP_E7SdKmiE4fRdE6dFannSkwSe63UGEsIk/edit#slide=id.g2e9e881f87b_0_0).

## Overview

As a _, I would like _, so that I can _.

## Context

*Optional: Any reference material or thoughts we may need for later reference, or assumptions of prior or future work that's out of scope for this story.*

- [ ]

## Acceptance Criteria

*Required outcomes of the story*

- [ ]

## Research Questions

- *Optional: Any initial questions for research*

## Tasks

*Research, design, and engineering work needed to complete the story.*

- [ ]

## Definition of done

The "definition of done" ensures our quality standards are met with each bit of user-facing behavior we add. Everything that can be done incrementally should be done incrementally, while the context and details are fresh. If it’s inefficient or “hard” to do so, the team should figure out why and add OPEX/DEVEX backlog items to make it easier and more efficient.

- [ ] Behavior
  - [ ] Acceptance criteria met
  - [ ] Implementation matches design decisions
- [ ] Documentation
  - [ ] ADRs (`/documents/adr` folder)
  - [ ] Relevant `README.md`(s)
- [ ] Code quality
  - [ ] Code refactored for clarity and no design/technical debt
  - [ ] Adhere to separation of concerns; code is not tightly coupled, especially to 3rd party dependencies; dependency rule followed
  - [ ] Code is reviewed by team member
  - [ ] Code quality checks passed
- [ ] Security and privacy
  - [ ] Automated security and privacy gates passed
- [ ] Testing tasks completed
  - [ ] Automated tests pass
  - [ ] Unit test coverage of our code >= 90%
- [ ] Build and deploy
  - [ ] Build process updated
  - [ ] API(s) are versioned
  - [ ] Feature toggles created and/or deleted. Document the feature toggle
  - [ ] Source code is merged to the main branch

## Decisions

- *Optional: Any decisions we've made while working on this story*

**Comment by JennyRichards-Flexion** [comment]
9/6/24: In conversation with Jim, this item is LOW priority.
