### ISSUE TITLE
As a form author, I need to style text elements on the form so that they draw attention and get special treatment.

### ISSUE THREAD

**Issue by emilylordahl** [GSA-TTS/atj-platform#257]
In concept testing, it was discovered that large page titles are typically the first thing people see to orient themselves and that meta information such as form dates, statutes, etc. may require special typographic treatment. In the next phase of designs:
- Continue to use [USWDS](https://designsystem.digital.gov/components/typography/#source-sans-pro) H1 styling for form page title.
- Provide flexibility to style text as various USWDS headers while maintaining accessibility best practices for page hierarchy. Meta information such as form dates, statutes, etc. may require special typographic treatment.

Explore the specific needs when it comes to meta information and design a typographic styling feature that meets said need. 
- Consider that form authors are not UX or product designers, so their knowledge of typographic hierarchy and accessibility is somewhat limited. Markdown is likely unfamiliar to this audience as a styling mechanism. I suggest instead using typographic patterns in tools like Notion or Google Docs (attached examples). Be sure to consider this when designing.

![Screenshot 2024-07-24 at 2 08 02 PM](https://github.com/user-attachments/assets/60cf6f11-a261-4d84-8cb2-614cdef585f8)
![Screenshot 2024-07-24 at 2 08 48 PM](https://github.com/user-attachments/assets/a5d4df2b-3bea-4f5d-b304-3fd4ccdda069)

@jimmoffet This issue was added as a result of the UX Concept testing in https://github.com/GSA-TTS/atj-platform/issues/116 . It needs further refinement and prioritization.

UX considers this a minor feature/issue due to it coming up with some participants. Review details from the research in the [research report](https://docs.google.com/presentation/d/1qmmtHEboGP_E7SdKmiE4fRdE6dFannSkwSe63UGEsIk/edit#slide=id.g2e9e881f87b_0_20).

**Comment by JennyRichards-Flexion** [comment]
9/6/24: Per convo with Jim, this is related to [rich text editor issue](https://github.com/GSA-TTS/atj-platform/issues/296). Moved to In Review.
