### ISSUE TITLE
Move splash page to become home page for DOJ app

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#276]
As a form author, I need a way to login to the platform so that I can store my form drafts securely and return to them when I’m ready.

This is also related to #92 We may want to do a content review when this is ready and see if it meets the need identified there.

- [ ] Needs a new video

Design:
- [x] Collect references for similar SaaS product splash pages, such as https://designsystem.digital.gov/templates/landing-page/
- [x] Mock as above, pull content from here: https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/site/gsa-tts/atj-platform/splash
- [ ] CURRENT BRANCH LINK:  https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/add-homepage-content-to-splash-page/splash/

Eng:
- [ ] Move to new location
- [ ] Update based on design mock

**Comment by emilylordahl** [comment]
Hey @jimmoffet  and @natashapl, here are mocks for the [desktop landing page](https://www.figma.com/design/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=1191-27107&m=dev) and some [supporting component variations](https://www.figma.com/design/RAm1GWbVTdBpzlmaLL6pLO/ATJ-Platform?node-id=1193-32532&m=dev) across desktop and mobile. I didn't have time to do the full mobile mocks, so let me know if you need more support there (but hopefully it's straightforward enough of a page to breakdown without mocks :-/ ).

Let me know if any questions or feedback. Thanks!
