### ISSUE TITLE
UX Teardowns for [no-code form builder] products that share our current scope

### ISSUE THREAD

**Issue by jimmoffet** [GSA-TTS/atj-platform#60]
Note: not focusing on pdf ingestion for now.

What: A couple of UX Teardowns of relevant products. 

Why: Prior to actually testing with users, we want to avoid getting overly invested in UI decisions and we want to steal as many UX hours from other teams as we can.

Note: we have a couple of relatively-extensive teardowns of DocAssemble and ATJAuthor (no code docassemble)

Definition of done: 2(ish) well-annotated teardowns. Maybe JotForm (big scope), Google Forms (smaller scope). Build alabama name change in these two products, with notes and screenshots. Don't worry about anything that isn't strictly required to build that form. Don't worry too much about presentation, knowledge transfer is the key and it will happen while speaking over the accumulated notes/screenshots

**Comment by emilylordahl** [comment]
Hi @espythomson, I finished up the teardowns for JotForm and FormsSG. Let me know if you need support on Google Forms and Typeform! We can catch up on this on Monday. Looking forward to see what we both learned. 🤓

**Comment by emilylordahl** [comment]
Hi all—here is the result of the [heuristic eval](https://docs.google.com/spreadsheets/d/12lIfVLok9q5Dq48GxVQmPX-fgJEvc_lFOm8jHImysWo/edit#gid=185717474). To stay on track, the evaluation focused on CRUD of form questions but captured additional observations to get to that point in the flow. 

Based on this analysis, the average grade of the four platforms evaluated (GoogleForms, JotForm, TypeForm, Forms Singpore) was a B, so we have good reference points from these market tools. However, there is of course still room to improve—the recommendation is prioritize accessibility and usability as P0s and controllability and clarity as P1s. The full details recommendation details for each platform evaluated can be found in the platform respective tabs of the sheet linked on this ticket. 

Closing!
