### ISSUE TITLE
Basic conditional flow

### ISSUE THREAD

**Issue by danielnaab** [GSA-TTS/atj-platform#74]
As a content author, I would like to ask SRLs a clarifying question, so I ask appropriate questions for their particular circumstance.

Acceptance criteria:

- [ ] A method of conditionally displaying questions is implemented

**Comment by JennyRichards-Flexion** [comment]
9/6/24: Per conversation with Jim, this is a duplicate of [issue 288](https://github.com/GSA-TTS/atj-platform/issues/288). Closing as Dupe.
